# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201cf97f721c6bac2adf2447874c8908d06879481d4c59a35dd6cf7d73f7ead4de28004d9f4683b8224cde42e83d70c6ba7c0d74d00f1a6eb09aa00b8f06dbdd

test:
  secret_key_base: 8435613002b9ba1b04fbb808b4418714027a35563fc61e7106616029927e2b390ee63ffde42462c7e18b4d3d1b21fbb5ebc51acee907b9a212c367556f635caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
